# DEVELOPMENT ENV
development:
  NODE_ENV: development
  SERVICE_NAME: users
  PORT: 5001
  AUTH_JWT_SECRET: mysecretkey
  DB_USERS_TABLE_NAME: users-users-development

# PRODUCTION ENV
production:
  NODE_ENV: production
  SERVICE_NAME: users
  AWS_AKID: null # to be defined with secrets manager
  AWS_SAK: null # to be defined with secrets manager
  AUTH_JWT_SECRET: null # to be defined with secrets manager
  DB_USERS_TABLE_NAME: users-users-production
