# DEVELOPMENT ENV
development:
  NODE_ENV: development
  SERVICE_NAME: auth
  PORT: 5002
  AUTH_JWT_SECRET: mysecretkey
  DB_TOKENS_TABLE_NAME: auth-tokens-development

# PRODUCTION ENV
production:
  NODE_ENV: production
  SERVICE_NAME: auth
  AUTH_JWT_SECRET: mysecretkey
  AWS_AKID: null # to be defined with secrets manager
  AWS_SAK: null # to be defined with secrets manager
  DB_TOKENS_TABLE_NAME: auth-tokens-production