service: ${self:custom.environment.SERVICE_NAME}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-env-generator
  - serverless-plugin-monorepo

package:
  exclude:
    - fixtures/**
    - '**/__tests__/**'
    - '**/__mocks__/**'
    - aws.config.yml
    - backlog.todo
    - environment.yml
    - index.js
    - jest.config.js
    - package.json
    - README.md
    - yarn-error.log

custom:
  environment: ${file(environment.yml):${opt:stage, 'development'}}
  envFiles: # for serverless-env-generator plugin
    - environment.yml
  envEncryptionKeyId: ${file(aws.config.yml):KMS_KEY_ID}
  serverless-offline:
    port: ${self:custom.environment.PORT}
  awsConfig: ${file(aws.config.yml):${opt:stage, 'development'}}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'development'}
  profile: hawaii.js
  region: ${opt:region, 'eu-north-1'}
  usagePlan: ${self:custom.awsConfig.LAMBDA.USAGE_PLAN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.environment.DB_TOKENS_TABLE_NAME}"

functions:
  app:
    handler: serverless.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  login:
    handler: serverless.handler
    events:
      - http: 'POST auth/login'
  confirm:
    handler: serverless.handler
    events:
      - http: 'GET auth/confirm'
  refresh:
    handler: serverless.handler
    events:
      - http: 'POST auth/refresh'

resources:
  Resources:
    tokensTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.environment.DB_TOKENS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: uid
            AttributeType: S
        KeySchema:
          - AttributeName: uid
            KeyType: HASH
        ProvisionedThroughput: ${self:custom.awsConfig.DYNAMODB.TOKENS_TABLE.TABLE_THROUGHPUT}